version: '3.8'
services:
  frontend:
    container_name: client
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    container_name: server
    build:
      context: ./server
    ports:
      - "5000:5000"
